### ISSUE TITLE
Selección de una fuente de datos 

### ISSUE THREAD

**Issue by Dacoher** [DanielGlezDeChavesGonzalez/TFG_redes_neuronales#1]
## Descripción
Investigar e identificar posibles fuentes de datos para realizar las predicciones. Se debería de evaluar cada fuente para determinar la calidad, disponibilidad y relevancia de los datos para los objetivos del proyecto.

## Subtareas
- [x]  Identificar al menos 2 fuentes de datos validas
- [x] Evaluar la calidad y cantidad de datos de cada fuente
- [x] Evaluar la facilidad de recopilación de los datos y las consideraciones legales.
- [x] Elaborar un pequeño documento con las conclusiones obtenidas

**Comment by DanielGlezDeChavesGonzalez** [comment]
Terminado y listo en el drive: https://drive.google.com/drive/folders/1fhWC0iNbRH8xKFqZXl0LFOf6hH4h3Doj?usp=drive_link

**Comment by DanielGlezDeChavesGonzalez** [comment]
Terminado y listo en el drive: https://drive.google.com/drive/folders/1fhWC0iNbRH8xKFqZXl0LFOf6hH4h3Doj?usp=drive_link
