### ISSUE TITLE
Análisis comparativo del framework de Deep Learning a usar

### ISSUE THREAD

**Issue by Dacoher** [DanielGlezDeChavesGonzalez/TFG_redes_neuronales#2]
## Descripción
Se debe realizar un análisis detallado de los frameworks más populares (como TensorFlow, PyTorch, Keras) para determinar cuál es el más adecuado para este proyecto. Los factores a considerar incluyen el soporte de la comunidad, la facilidad de uso, el rendimiento y la escalabilidad.

## Subtareas

- [x]  Comparar al menos tres frameworks diferentes.
- [x]  Elaborar un pequeño documento con las conclusiones obtenidas

**Comment by DanielGlezDeChavesGonzalez** [comment]
Finalizado en: https://docs.google.com/document/d/1TYnojqSoTEtXq8xhVAas4uXwrm0PSdv-rzJrGHaMgHQ/edit?usp=drive_link
