### ISSUE TITLE
Selección y justificación de la tecnología de bases de datos.

### ISSUE THREAD

**Issue by Dacoher** [DanielGlezDeChavesGonzalez/TFG_redes_neuronales#3]
## Descripción
Se debe Investigar y seleccionar la tecnología de base de datos más adecuada (SQL frente a NoSQL, etc.) para manejar datos de series temporales de manera eficiente. Justifica la elección en función del rendimiento, la escalabilidad y las capacidades de integración con el framework de Deep Learning elegido.

## Subtareas

- [x]  Evalúa el modelo de datos con el que vamos a trabajar y los requisitos de consulta.
- [x]  Identifica las entidades y relaciones esenciales para el proyecto.
- [x]  Diseña un diagrama entidad-relación (ERD).
- [x]  Compara diferentes tecnologías de base de datos para determinar su idoneidad.
- [x] Investiga posibles estrategias de optimización que puedan ayudar cuando la cantidad de registros es muy elevada
- [x]  Elaborar un pequeño documento con las conclusiones obtenidas

**Comment by DanielGlezDeChavesGonzalez** [comment]
hecho en: https://docs.google.com/document/d/1N7SJWIRUO5Gr2qmQMuJgm-vto-NB-aXfLsC9pREf4b4/edit?usp=drive_link

**Comment by Dacoher** [comment]
Adjunto dos scripts de ejemplos. El primero hace un empaquetado básico de los datos en dos formatos (TFRecords y npz) y el segundo crea un generador de datos que debería de ser compatible con los modelos que vayamos a definir a continuación. 

[ejemplos.zip](https://github.com/DanielGlezDeChavesGonzalez/TFG_redes_neuronales/files/14649600/ejemplos.zip)

**Comment by Dacoher** [comment]
@DanielGlezDeChavesGonzalez
