### ISSUE TITLE
 Estudio de viabilidad de integración de Docker

### ISSUE THREAD

**Issue by Dacoher** [DanielGlezDeChavesGonzalez/TFG_redes_neuronales#4]
## Descripción
Explora la viabilidad y las ventajas de utilizar Docker para la virtualización de entornos. Investiga el potencial para mejorar la reproducibilidad y la facilidad de configuración en diferentes entornos de desarrollo.

## Subtareas

- [x]  Explora las capacidades y limitaciones de Docker.
- [x]  Crea una prueba de concepto para la integración de Docker.
- [x] Elaborar un pequeño documento con las conclusiones obtenidas

**Comment by DanielGlezDeChavesGonzalez** [comment]
https://docs.google.com/document/d/1vWHpMZOSqFym-qYKBaGB147hNVN7tgzDry7TSrT1yPc/edit?usp=drive_link
