### ISSUE TITLE
Desarrollo de un pipeline de cargado de datos

### ISSUE THREAD

**Issue by Dacoher** [DanielGlezDeChavesGonzalez/TFG_redes_neuronales#5]
## Descripción
Desarrollar un proceso de preprocesamiento de datos que incluya limpieza, normalización y transformación de datos. El proceso debe de ser modular y poder adaptarse a las fuentes de datos seleccionadas. Al ejecutarse este proceso se debe de poblar una base de datos.

## Subtareas

- [x] Estudiar las técnicas de normalización y transformación más comunes en las series de datos temporales.
- [x] Estudiar las técnicas de aumento de datos más comunes en las series de datos temporales
- [x] Desarrollar un proceso para poblar una base de datos implementando algunas de las técnicas seleccionadas (se debe de poder seleccionar que técnicas se desea aplicar)
- [x] Dockerizar el proceso (**opcional**) 
- [x] Implementar mecanismos de logging y gestión de errores en el proceso de poblado de la base datos. (**opcional**)

**Comment by Dacoher** [comment]
Para elaborar una interfaz de línea de comandos te recomiendo que hagas uso del paquete [click](https://github.com/pallets/click) aunque tienes alternativas como [typer](https://github.com/tiangolo/typer) o las herramientas de la librería estándar de python.

**Comment by DanielGlezDeChavesGonzalez** [comment]
https://docs.google.com/document/d/12IIzxfvIENblDGQ3yM3ujHbEwkI0DVSrxLUPMW3I3qY/edit?usp=sharing
